data:
  train:
    - data/raw/HIPE-2026-data/data/sandbox/en-train.jsonl
    - data/raw/HIPE-2026-data/data/sandbox/de-train.jsonl
    - data/raw/HIPE-2026-data/data/sandbox/fr-train.jsonl
  dev:
    - data/raw/HIPE-2026-data/data/newspapers/v1.0/HIPE-2026-v1.0-impresso-train-en.jsonl
    - data/raw/HIPE-2026-data/data/newspapers/v1.0/HIPE-2026-v1.0-impresso-train-de.jsonl
    - data/raw/HIPE-2026-data/data/newspapers/v1.0/HIPE-2026-v1.0-impresso-train-fr.jsonl
consistency: "off"
model:
  name: llm_lookup
  label_source:
    - data/raw/HIPE-2026-data/data/sandbox/en-train.jsonl
    - data/raw/HIPE-2026-data/data/sandbox/de-train.jsonl
    - data/raw/HIPE-2026-data/data/sandbox/fr-train.jsonl
    - data/raw/HIPE-2026-data/data/sandbox/en-dev.jsonl
    - data/raw/HIPE-2026-data/data/sandbox/de-dev.jsonl
    - data/raw/HIPE-2026-data/data/sandbox/fr-dev.jsonl
