data:
  train:
    - data/raw/HIPE-2026-data/data/sandbox/en-train.jsonl
    - data/raw/HIPE-2026-data/data/sandbox/de-train.jsonl
    - data/raw/HIPE-2026-data/data/sandbox/fr-train.jsonl
  dev:
    - data/raw/HIPE-2026-data/data/newspapers/v1.0/HIPE-2026-v1.0-impresso-train-en.jsonl
    - data/raw/HIPE-2026-data/data/newspapers/v1.0/HIPE-2026-v1.0-impresso-train-de.jsonl
    - data/raw/HIPE-2026-data/data/newspapers/v1.0/HIPE-2026-v1.0-impresso-train-fr.jsonl
consistency: soft
model:
  name: embedding_svm
  model_name: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
  C: 1.0
  use_structural: true
